#!/bin/sh
for f in *; do
    if [ -d $f ]; then
        cd $f
        echo "======"
        echo "REPO: [$(pwd)]"
        #pwd
        #echo "]"
        echo $@
        $@
        echo
        cd ..
    fi
done
