#!/bin/bash
# vim: syntax=sh

. /etc/rc.conf
. /etc/rc.d/functions

NGINX=/usr/local/nginx/sbin/nginx
DAEMON=nginx
PID=$(pidof $NGINX)
case "$1" in
  start)
    stat_busy "Starting $DAEMON"
    [ -z "$PID" ] && $NGINX  > /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon $DAEMON
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping $DAEMON"
    [ ! -z "$PID" ] && kill -9 $PID
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon $DAEMON
      while [ ! -z "$(pidof $NGINX)" ]; do
        sleep 1;
      done
      stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
