#!/usr/bin/env bash

# settings
export HISTTIMEFORMAT="%Y/%d/%m %T "    # display time in bash history
export PAGER=/usr/bin/less
export VISUAL=vim

# turn off the annoying beep
xset -b

# remove bind for Ctrl-L for Cursor
bind -r '\C-l'

# aliases
alias diff='diff -u'
alias dirs='dirs -v'
alias emacs='emacs -nw'
alias grep='grep --color=auto'
alias jobs='jobs -l'
alias la='ls -a'
alias ll='ls -l'
alias ls='ls --color=auto'
alias psc='ps xawf -eo pid,user,cgroup,args'
alias tig='tig --all'
alias vi='vim'

# PS1
parse_git_branch() {
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/[\1]/'
}
find_git_branch () {
    local dir=. head
    until [ "$dir" -ef / ]; do
        if [ -f "$dir/.git/HEAD" ]; then
            head=$(< "$dir/.git/HEAD")
            if [[ $head = ref:\ refs/heads/* ]]; then
                git_branch="[${head#*/*/}]"
            elif [[ $head != '' ]]; then
                git_branch="[(detached)]"
            else
                git_branch="[(unknown)]"    # →
            fi
            return
        fi
        dir="../$dir"
    done
    git_branch=''
}
PROMPT_COMMAND="find_git_branch; $PROMPT_COMMAND"

# Here is bash color codes you can use
  black=$'\[\e[1;30m\]'
    red=$'\[\e[1;31m\]'
  green=$'\[\e[1;32m\]'
 yellow=$'\[\e[1;33m\]'
   blue=$'\[\e[1;34m\]'
magenta=$'\[\e[1;35m\]'
   cyan=$'\[\e[1;36m\]'
  white=$'\[\e[1;37m\]'
 normal=$'\[\e[m\]'

PS1="$normal[\u:\W]$green\$git_branch$white\$ $normal"
